'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace UFId.DAL

    Partial Public Class ObjectEditStatus
        Inherits DevExpress.Persistent.BaseImpl.BaseObject
        Dim _Code As String
        Public Property Code() As String
            Get
                Return _Code
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Code", _Code, value)
            End Set
        End Property
        Dim _Caption As String
        Public Property Caption() As String
            Get
                Return _Caption
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Caption", _Caption, value)
            End Set
        End Property
        Dim _Index As Decimal
        Public Property Index() As Decimal
            Get
                Return _Index
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Index", _Index, value)
            End Set
        End Property
        Dim _Status As AcurSoft.Enums.ObjectEditStatuses
        Public Property Status() As AcurSoft.Enums.ObjectEditStatuses
            Get
                Return _Status
            End Get
            Set(ByVal value As AcurSoft.Enums.ObjectEditStatuses)
                SetPropertyValue(Of AcurSoft.Enums.ObjectEditStatuses)("Status", _Status, value)
            End Set
        End Property
    End Class

End Namespace
