'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace UFId.DAL

    Partial Public Class UFIdSequenceParamValue
        Inherits DevExpress.Persistent.BaseImpl.BaseObject
        Dim _LinkParam As UFIdConfigLinkParam
        <Association("UFIdSequenceParamValueReferencesUFIdConfigLinkParam")>
        Public Property LinkParam() As UFIdConfigLinkParam
            Get
                Return _LinkParam
            End Get
            Set(ByVal value As UFIdConfigLinkParam)
                SetPropertyValue(Of UFIdConfigLinkParam)("LinkParam", _LinkParam, value)
            End Set
        End Property
        Dim _Sequence As UFIdSequence
        <Association("UFIdSequenceParamValueReferencesUFIdSequence")>
        Public Property Sequence() As UFIdSequence
            Get
                Return _Sequence
            End Get
            Set(ByVal value As UFIdSequence)
                SetPropertyValue(Of UFIdSequence)("Sequence", _Sequence, value)
            End Set
        End Property
        Dim _ParamValue As String
        Public Property ParamValue() As String
            Get
                Return _ParamValue
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ParamValue", _ParamValue, value)
            End Set
        End Property
    End Class

End Namespace
