'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace UFId.DAL

    Partial Public Class UFIdSequence
        Inherits DevExpress.Persistent.BaseImpl.BaseObject
        Dim _Link As UFIdConfigLink
        <Association("UFIdSequenceReferencesUFIdConfigLink")>
        Public Property Link() As UFIdConfigLink
            Get
                Return _Link
            End Get
            Set(ByVal value As UFIdConfigLink)
                SetPropertyValue(Of UFIdConfigLink)("Link", _Link, value)
            End Set
        End Property
        Dim _DateValue As DateTime
        Public Property DateValue() As DateTime
            Get
                Return _DateValue
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("DateValue", _DateValue, value)
            End Set
        End Property
        Dim _NumValue As Long
        Public Property NumValue() As Long
            Get
                Return _NumValue
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("NumValue", _NumValue, value)
            End Set
        End Property
        Dim _UFIdDateText As String
        Public Property UFIdDateText() As String
            Get
                Return _UFIdDateText
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("UFIdDateText", _UFIdDateText, value)
            End Set
        End Property
        Dim _UFIdText As String
        Public Property UFIdText() As String
            Get
                Return _UFIdText
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("UFIdText", _UFIdText, value)
            End Set
        End Property
        Dim _TargetId As Guid
        Public Property TargetId() As Guid
            Get
                Return _TargetId
            End Get
            Set(ByVal value As Guid)
                SetPropertyValue(Of Guid)("TargetId", _TargetId, value)
            End Set
        End Property
        Dim _Status As AcurSoft.UFId.Enums.SequenceStatuses
        Public Property Status() As AcurSoft.UFId.Enums.SequenceStatuses
            Get
                Return _Status
            End Get
            Set(ByVal value As AcurSoft.UFId.Enums.SequenceStatuses)
                SetPropertyValue(Of AcurSoft.UFId.Enums.SequenceStatuses)("Status", _Status, value)
            End Set
        End Property
    End Class

End Namespace
