'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace UFId.DAL

    Partial Public Class UFIdConfigLinkParam
        Inherits DevExpress.Persistent.BaseImpl.BaseObject
        Dim _Link As UFIdConfigLink
        <Association("UFIdConfigLinkParamReferencesUFIdConfigLink")>
        Public Property Link() As UFIdConfigLink
            Get
                Return _Link
            End Get
            Set(ByVal value As UFIdConfigLink)
                SetPropertyValue(Of UFIdConfigLink)("Link", _Link, value)
            End Set
        End Property
        Dim _Code As String
        Public Property Code() As String
            Get
                Return _Code
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Code", _Code, value)
            End Set
        End Property
        Dim _Expression As String
        Public Property Expression() As String
            Get
                Return _Expression
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Expression", _Expression, value)
            End Set
        End Property
        Dim _Type As AcurSoft.Enums.BasicTypeCode
        Public Property Type() As AcurSoft.Enums.BasicTypeCode
            Get
                Return _Type
            End Get
            Set(ByVal value As AcurSoft.Enums.BasicTypeCode)
                SetPropertyValue(Of AcurSoft.Enums.BasicTypeCode)("Type", _Type, value)
            End Set
        End Property
        Dim _Index As Decimal
        Public Property Index() As Decimal
            Get
                Return _Index
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Index", _Index, value)
            End Set
        End Property
        <Association("UFIdSequenceParamValueReferencesUFIdConfigLinkParam"), Aggregated()>
        Public ReadOnly Property UFIdSequenceParamValues() As XPCollection(Of UFIdSequenceParamValue)
            Get
                Return GetCollection(Of UFIdSequenceParamValue)("UFIdSequenceParamValues")
            End Get
        End Property
    End Class

End Namespace
