'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace UFId.DAL

    Partial Public Class TestObject
        Inherits UFIdBaseObject
        Dim _Tdate As DateTime
        Public Property Tdate() As DateTime
            Get
                Return _Tdate
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("Tdate", _Tdate, value)
            End Set
        End Property
        Dim _Field1 As String
        Public Property Field1() As String
            Get
                Return _Field1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Field1", _Field1, value)
            End Set
        End Property
        Dim _Field2 As String
        Public Property Field2() As String
            Get
                Return _Field2
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Field2", _Field2, value)
            End Set
        End Property
        Dim _Field3 As String
        Public Property Field3() As String
            Get
                Return _Field3
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Field3", _Field3, value)
            End Set
        End Property
    End Class

End Namespace
