'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace DAL

    Partial Public Class ObjectTemplateChildMember
        Inherits XPObject
        Dim _ParentMember As ObjectTemplateMember
        <Association("ObjectTemplateChildMemberReferencesObjectTemplateMember")>
        Public Property ParentMember() As ObjectTemplateMember
            Get
                Return _ParentMember
            End Get
            Set(ByVal value As ObjectTemplateMember)
                SetPropertyValue(Of ObjectTemplateMember)("ParentMember", _ParentMember, value)
            End Set
        End Property
        Dim _MemberName As String
        Public Property MemberName() As String
            Get
                Return _MemberName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("MemberName", _MemberName, value)
            End Set
        End Property
        Dim _MemberType As String
        Public Property MemberType() As String
            Get
                Return _MemberType
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("MemberType", _MemberType, value)
            End Set
        End Property
        Dim _UseKey As Boolean
        Public Property UseKey() As Boolean
            Get
                Return _UseKey
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("UseKey", _UseKey, value)
            End Set
        End Property
        Dim _AllowEdit As Boolean
        Public Property AllowEdit() As Boolean
            Get
                Return _AllowEdit
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("AllowEdit", _AllowEdit, value)
            End Set
        End Property
        Dim _Index As Decimal
        Public Property Index() As Decimal
            Get
                Return _Index
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Index", _Index, value)
            End Set
        End Property
        <Association("ObjectTemplateChildMemberValueReferencesObjectTemplateChildMember"), Aggregated()>
        Public ReadOnly Property ObjectTemplateChildMemberValues() As XPCollection(Of ObjectTemplateChildMemberValue)
            Get
                Return GetCollection(Of ObjectTemplateChildMemberValue)("ObjectTemplateChildMemberValues")
            End Get
        End Property
    End Class

End Namespace
