'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace DAL

    Partial Public Class ObjectTemplateMember
        Inherits DevExpress.Persistent.BaseImpl.BaseObject
        Dim _Template As ObjectTemplate
        <Association("ObjectTemplateMemberReferencesObjectTemplate")>
        Public Property Template() As ObjectTemplate
            Get
                Return _Template
            End Get
            Set(ByVal value As ObjectTemplate)
                SetPropertyValue(Of ObjectTemplate)("Template", _Template, value)
            End Set
        End Property
        Dim _MemberName As String
        Public Property MemberName() As String
            Get
                Return _MemberName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("MemberName", _MemberName, value)
            End Set
        End Property
        Dim _MemberType As String
        Public Property MemberType() As String
            Get
                Return _MemberType
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("MemberType", _MemberType, value)
            End Set
        End Property
        Dim _UseKey As Boolean
        Public Property UseKey() As Boolean
            Get
                Return _UseKey
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("UseKey", _UseKey, value)
            End Set
        End Property
        Dim _MemberValue As String
        <Size(SizeAttribute.Unlimited)>
        Public Property MemberValue() As String
            Get
                Return _MemberValue
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("MemberValue", _MemberValue, value)
            End Set
        End Property
        Dim _IsAssociation As Boolean
        Public Property IsAssociation() As Boolean
            Get
                Return _IsAssociation
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsAssociation", _IsAssociation, value)
            End Set
        End Property
        Dim _AllowEdit As Boolean
        Public Property AllowEdit() As Boolean
            Get
                Return _AllowEdit
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("AllowEdit", _AllowEdit, value)
            End Set
        End Property
        Dim _SubValuesCount As Integer
        Public Property SubValuesCount() As Integer
            Get
                Return _SubValuesCount
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("SubValuesCount", _SubValuesCount, value)
            End Set
        End Property
        Dim _Index As Decimal
        Public Property Index() As Decimal
            Get
                Return _Index
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Index", _Index, value)
            End Set
        End Property
        <Association("ObjectTemplateChildMemberValueReferencesObjectTemplateMember")>
        Public ReadOnly Property ObjectTemplateChildMemberValues() As XPCollection(Of ObjectTemplateChildMemberValue)
            Get
                Return GetCollection(Of ObjectTemplateChildMemberValue)("ObjectTemplateChildMemberValues")
            End Get
        End Property
        <Association("ObjectTemplateChildMemberReferencesObjectTemplateMember"), Aggregated()>
        Public ReadOnly Property ObjectTemplateChildMembers() As XPCollection(Of ObjectTemplateChildMember)
            Get
                Return GetCollection(Of ObjectTemplateChildMember)("ObjectTemplateChildMembers")
            End Get
        End Property
    End Class

End Namespace
